[mongodb]
localhost

# [catalogue]
# catalogue.devopsrank.online

# [cart]
# cart.devopsrank.online

# [user]
# user.devopsrank.online

[redis]
localhost

[mysql]
localhost

# [shipping]
# shipping.devopsrank.online

# [payment]
# payments.devopsrank.online

[rabbitmq]
localhost

# [web]
# web.devopsrank.online

# [dispatch]
# dispatch.devopsrank.online

# ;  [all:vars]
# ;  ansible_password=DevOps321